server:
  port: 8080
spring:
  profiles:
    active: mailmanager
  main:
    banner-mode: off
  application:
    name: "Lsk-services"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: Lsk-service api doc
  try-host: http://localhost:${server.port}